# Generated by Django 4.1.7 on 2024-03-11 17:32

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Article Title"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Article Description"
                    ),
                ),
                ("body", models.TextField(verbose_name="Article Body")),
                (
                    "banner_image",
                    models.ImageField(
                        default="/article-default.png",
                        upload_to="",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "body_image_1",
                    models.ImageField(
                        default="/article-default.png",
                        upload_to="",
                        verbose_name="Body Image 1",
                    ),
                ),
                (
                    "body_image_2",
                    models.ImageField(
                        default="/article-default.png",
                        upload_to="",
                        verbose_name="Body Image 2",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.CreateModel(
            name="ArticleViews",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "viewer_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Viewer IP"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_views",
                        to="articles.article",
                        verbose_name="Article being viewed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_viewed_article",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Article viewd by User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article View",
                "verbose_name_plural": "Article Views",
                "unique_together": {("article", "user", "viewer_ip")},
            },
        ),
    ]
