# Generated by Django 4.1.7 on 2024-03-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/default-user-image.jpg",
                null=True,
                upload_to="CustomUsers/ProfilePictures/",
                verbose_name="Profile Picture",
            ),
        ),
    ]
