# Generated by Django 4.1.7 on 2024-03-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/default-user-image.jpg",
                null=True,
                upload_to="CustomUsers/UserImage/",
                verbose_name="Profile Picture",
            ),
        ),
    ]
