# Generated by Django 4.1.7 on 2024-03-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_image",
            field=models.ImageField(
                blank=True,
                default="/default-user-image.jpg",
                null=True,
                upload_to="CustomUsers/UserImage/",
                verbose_name="User Image Profile Picture",
            ),
        ),
    ]
