# Generated by Django 4.1.7 on 2024-03-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_customuser_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_image",
            field=models.ImageField(
                blank=True,
                default="default_user_image.jpg",
                null=True,
                upload_to="CustomUsers/UserImage/",
                verbose_name="User Image Profile Picture",
            ),
        ),
    ]
