# Generated by Django 4.1.7 on 2024-03-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/default-user-image.jpg",
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
    ]
