# Generated by Django 4.1.7 on 2024-03-08 09:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter_handle",
            field=models.CharField(
                blank=True, default="", max_length=25, verbose_name="Twitter/X Handle"
            ),
        ),
    ]
