#!/usr/bin/env bash 


# the main backup scripts to backup postgres database 

set -o errexit 
set -o nounset
set -o pipefail 

# get the currect file address
work_dir="$(dirname ${0})"

# import necessary files 
source "${work_dir}/_sourced/constants.sh"
source "${work_dir}/_sourced/messages.sh"


message_welcome "Backing up the '${POSTGRES_DB}' database ... "

# default postgres user is not allowed to backup
if [[ "${POSTGRES_USER}" == "postgres" ]]; then 
    message_error "Backing up as default 'postgres' user is not allowed. Assign 'POSTGRES_USER' in env file with custom user."
    exit 1 
fi 



# exporinting the postgres credentials 
export PGHOST="${POSTGRES_HOST}"
export PGPORT="${POSTGRES_PORT}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"


backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"

# pg_dump bash command and compress the backup with gzip 
# TODO review if the command should be passed as: pg_dump "${POSTGRES_DB}" | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"
pg_dump "${POSTGRES_DB}" | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"


message_success "'${POSTGRES_DB}' database backup '${backup_filename}' has been created successfully and stored in '${BACKUP_DIR_PATH}'"


