# Generated by Django 4.1.7 on 2024-03-17 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="context",
            new_name="content",
        ),
    ]
